### PR TITLE
fix: nondeterminism in renderer

### LINKED ISSUE #1312: Determinism is broken
#1287 broke determinism, as mentioned in https://github.com/penrose/penrose/pull/1294#issuecomment-1424859484.

### PR DESCRIPTION
**Pull request by wodeni**
# Description

Resolves #1312.

# Implementation strategy and design decisions

* In `Line.ts`, stop using `uuid.v4` for unique ID generation
* Instead, `Render*` functions take in `name`, a client-provided id for the diagram instance to be rendered. And names in the SVG are disambiguated from others instances by a unique instance id. 
* Similarly, `Simple` and `GridBox` take in `name` too.
* Remove `uuid` from `core`'s dependencies
* Note that this PR doesn't solve #1307

# Examples with steps to reproduce them

# Checklist

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new ESLint warnings
- [x] I have reviewed any generated registry diagram changes

# Open questions

Questions that require more discussion or to be addressed in future development:

### CODE REVIEW

**Comment by samestep** [comment]
Looks like `packages/core/package.json` changed but `yarn.lock` didn't; could you run `yarn`?

File: packages/core/src/index.ts [hunk 1]
```diff
@@ -176,13 +176,14 @@ export const diagram = async (
     variation: string;
   },
   node: HTMLElement,
-  pathResolver: PathResolver
+  pathResolver: PathResolver,
+  name: string
```
Comment (samestep) [inline packages/core/src/index.ts:180]: To make this a non-breaking change, we need to make this `name` parameter optional.

File: packages/core/src/index.ts [hunk 2]
```diff
@@ -207,14 +208,16 @@ export const interactiveDiagram = async (
...
```
Comment (samestep) [inline packages/core/src/index.ts:212]: Same here.

**Review by samestep — CHANGES_REQUESTED** [review]
Quick note about backwards compatibility before I review the rest.

**Comment by samestep** [comment]
I guess the `name` prop for the `Simple` component also needs to be optional.

**Review by samestep — APPROVED** [review]
Looks great, thanks!
